jobs:
  - job: Test
    pool:
      vmImage: 'Ubuntu 16.04'
    variables:
      NODE_VERSION: 12.16.1
      SPRING_OUTPUT_ANSI_ENABLED: NEVER
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
      NG_CLI_ANALYTICS: 'false'

    steps:
      #----------------------------------------------------------------------
      # Install all tools and check configuration
      #----------------------------------------------------------------------
      - task: NodeTool@0
        inputs:
          versionSpec: $(NODE_VERSION)
        displayName: 'TOOLS: install Node.js'
      #----------------------------------------------------------------------
      # Tests
      #----------------------------------------------------------------------
      - task: Npm@1
        inputs:
          command: 'install'
        displayName: 'INSTALL: launch npm install'
      - script: |
          chmod +x mvnw
          ./mvnw -ntp checkstyle:check
          ./mvnw -ntp clean verify -P-webpack
        displayName: 'TESTS: backend'
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run test'
        displayName: 'TESTS: frontend'
      - script: ./mvnw -ntp verify -Pprod -DskipTests
        displayName: 'TESTS: packaging'
      #----------------------------------------------------------------------
      # Production build
      #----------------------------------------------------------------------
      #doing a production build with JHipster.+ skiptest
      - script: ./mvnw package -Pprod -DskipTests
        displayName: 'BUILD: creating production build'
      #copy the generated  JAR file to a directory where artifacts are being stored.
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'target'
          Contents: '*.jar'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      #take that artifact and publish it.
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: SpringAzureApp
